export const userData = [
    {
        name: "Jan",
        "Active User": 4000,
    },
    {
        name: "Feb",
        "Active User": 3000,
    },
    {
        name: "Mar",
        "Active User": 2000,
    },
    {
        name: "Apr",
        "Active User": 2780,
    },
    {
        name: "May",
        "Active User": 1890,
    },
    {
        name: "Jun",
        "Active User": 2390,
    },
    {
        name: "Jul",
        "Active User": 1490,
    },
    {
        name: "Aug",
        "Active User": 3410,
    },
    {
        name: "Sep",
        "Active User": 3090,
    },
    {
        name: "Oct",
        "Active User": 3490,
    },
    {
        name: "Nov",
        "Active User": 3400,
    },
    {
        name: "Dec",
        "Active User": 3090,
    },
];

export const userRows = [
    {
        id: 1,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 2,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 3,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 4,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 5,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 6,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 7,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 8,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 9,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 10,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 11,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 12,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 13,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 14,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 15,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
    {
        id: 16,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "Jon123@gmail.com",
        status: "active",
        transaction: "$223",
    },
];
